//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CommonForms {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Locale {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Locale() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CommonForms.Locale", typeof(Locale).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ADD FILES.
        /// </summary>
        internal static string FILE_LIST_BUTTON_ADD {
            get {
                return ResourceManager.GetString("FILE_LIST_BUTTON_ADD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CLEAR.
        /// </summary>
        internal static string FILE_LIST_BUTTON_CLEAR {
            get {
                return ResourceManager.GetString("FILE_LIST_BUTTON_CLEAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -.
        /// </summary>
        internal static string FILE_LIST_BUTTON_REM {
            get {
                return ResourceManager.GetString("FILE_LIST_BUTTON_REM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ↓↓ Add Files To Merge ↓↓.
        /// </summary>
        internal static string FILE_LIST_LABEL_ADD {
            get {
                return ResourceManager.GetString("FILE_LIST_LABEL_ADD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folder was added..
        /// </summary>
        internal static string STATUS_FOLDER_ADDED {
            get {
                return ResourceManager.GetString("STATUS_FOLDER_ADDED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folder was not added..
        /// </summary>
        internal static string STATUS_FOLDER_NOT_ADDED {
            get {
                return ResourceManager.GetString("STATUS_FOLDER_NOT_ADDED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folder was reloaded..
        /// </summary>
        internal static string STATUS_FOLDER_RELOADED {
            get {
                return ResourceManager.GetString("STATUS_FOLDER_RELOADED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List was cleared..
        /// </summary>
        internal static string STATUS_LIST_CLEARED {
            get {
                return ResourceManager.GetString("STATUS_LIST_CLEARED", resourceCulture);
            }
        }
    }
}
