//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CommonForms {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Locale {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Locale() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CommonForms.Locale", typeof(Locale).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ADD.
        /// </summary>
        internal static string DLG_CHANGE_BUTTON_ADD_LABEL {
            get {
                return ResourceManager.GetString("DLG_CHANGE_BUTTON_ADD_LABEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPDATE.
        /// </summary>
        internal static string DLG_CHANGE_BUTTON_UPDATE_LABEL {
            get {
                return ResourceManager.GetString("DLG_CHANGE_BUTTON_UPDATE_LABEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something went wrong with the Change, it is not valid..
        /// </summary>
        internal static string DLG_CHANGE_ERR_MSG_CHANGE_WRONG {
            get {
                return ResourceManager.GetString("DLG_CHANGE_ERR_MSG_CHANGE_WRONG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Either disable the custom description or enter some text into the field.
        /// </summary>
        internal static string DLG_CHANGE_ERR_MSG_DESC {
            get {
                return ResourceManager.GetString("DLG_CHANGE_ERR_MSG_DESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Select An Action First!.
        /// </summary>
        internal static string DLG_CHANGE_ERR_MSG_SELECT_ACTION {
            get {
                return ResourceManager.GetString("DLG_CHANGE_ERR_MSG_SELECT_ACTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Select A Condition First!.
        /// </summary>
        internal static string DLG_CHANGE_ERR_MSG_SELECT_CONDITION {
            get {
                return ResourceManager.GetString("DLG_CHANGE_ERR_MSG_SELECT_CONDITION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom description is empty..
        /// </summary>
        internal static string DLG_CHANGE_ERR_TITILE_DESC {
            get {
                return ResourceManager.GetString("DLG_CHANGE_ERR_TITILE_DESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action is not valid.
        /// </summary>
        internal static string DLG_CHANGE_ERR_TITLE_ACTION_NOT_VALID {
            get {
                return ResourceManager.GetString("DLG_CHANGE_ERR_TITLE_ACTION_NOT_VALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Condition is not valid.
        /// </summary>
        internal static string DLG_CHANGE_ERR_TITLE_CONDITION_NOT_VALID {
            get {
                return ResourceManager.GetString("DLG_CHANGE_ERR_TITLE_CONDITION_NOT_VALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string DLG_CHANGE_ERR_TITLE_ERROR {
            get {
                return ResourceManager.GetString("DLG_CHANGE_ERR_TITLE_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        internal static string DLG_CHANGE_ERR_TITLE_WARNING {
            get {
                return ResourceManager.GetString("DLG_CHANGE_ERR_TITLE_WARNING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Change.
        /// </summary>
        internal static string DLG_CHANGE_TITLE_ADD {
            get {
                return ResourceManager.GetString("DLG_CHANGE_TITLE_ADD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Change.
        /// </summary>
        internal static string DLG_CHANGE_TITLE_EDIT {
            get {
                return ResourceManager.GetString("DLG_CHANGE_TITLE_EDIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folder must exist.
        /// </summary>
        internal static string EDITOR_COPYFILE_ERROR_FOLDER_NOT_EXIST {
            get {
                return ResourceManager.GetString("EDITOR_COPYFILE_ERROR_FOLDER_NOT_EXIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select the folder where to copy the files.
        /// </summary>
        internal static string EDITOR_COPYFILE_ERROR_SELECT_FOLDER {
            get {
                return ResourceManager.GetString("EDITOR_COPYFILE_ERROR_SELECT_FOLDER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must add at least one extension..
        /// </summary>
        internal static string EDITOR_HAS_EXTENSION_ERR_MSG_MUST_ADD_EXT {
            get {
                return ResourceManager.GetString("EDITOR_HAS_EXTENSION_ERR_MSG_MUST_ADD_EXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ADD FILES.
        /// </summary>
        internal static string FILE_LIST_BUTTON_ADD {
            get {
                return ResourceManager.GetString("FILE_LIST_BUTTON_ADD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CLEAR.
        /// </summary>
        internal static string FILE_LIST_BUTTON_CLEAR {
            get {
                return ResourceManager.GetString("FILE_LIST_BUTTON_CLEAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -.
        /// </summary>
        internal static string FILE_LIST_BUTTON_REM {
            get {
                return ResourceManager.GetString("FILE_LIST_BUTTON_REM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ↓↓ Add Files ↓↓ .
        /// </summary>
        internal static string FILE_LIST_LABEL_ADD {
            get {
                return ResourceManager.GetString("FILE_LIST_LABEL_ADD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ADD FILES.
        /// </summary>
        internal static string FILES_LIST_BUTTON_ADD {
            get {
                return ResourceManager.GetString("FILES_LIST_BUTTON_ADD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CLEAR.
        /// </summary>
        internal static string FILES_LIST_BUTTON_CLEAR {
            get {
                return ResourceManager.GetString("FILES_LIST_BUTTON_CLEAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -.
        /// </summary>
        internal static string FILES_LIST_BUTTON_REM {
            get {
                return ResourceManager.GetString("FILES_LIST_BUTTON_REM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT ALL.
        /// </summary>
        internal static string FILES_LIST_BUTTON_SELECT_ALL {
            get {
                return ResourceManager.GetString("FILES_LIST_BUTTON_SELECT_ALL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LIST SETTINGS.
        /// </summary>
        internal static string FILES_LIST_BUTTON_SETTINGS {
            get {
                return ResourceManager.GetString("FILES_LIST_BUTTON_SETTINGS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ↓↓ Add Files To Merge ↓↓.
        /// </summary>
        internal static string FILES_LIST_LABEL_ADD {
            get {
                return ResourceManager.GetString("FILES_LIST_LABEL_ADD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List ready..
        /// </summary>
        internal static string FILES_LIST_STATUS_READY {
            get {
                return ResourceManager.GetString("FILES_LIST_STATUS_READY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folder added..
        /// </summary>
        internal static string STATUS_FOLDER_ADDED {
            get {
                return ResourceManager.GetString("STATUS_FOLDER_ADDED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folder not added..
        /// </summary>
        internal static string STATUS_FOLDER_NOT_ADDED {
            get {
                return ResourceManager.GetString("STATUS_FOLDER_NOT_ADDED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folder reloaded..
        /// </summary>
        internal static string STATUS_FOLDER_RELOADED {
            get {
                return ResourceManager.GetString("STATUS_FOLDER_RELOADED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List cleared..
        /// </summary>
        internal static string STATUS_LIST_CLEARED {
            get {
                return ResourceManager.GetString("STATUS_LIST_CLEARED", resourceCulture);
            }
        }
    }
}
